# -*- coding: utf-8 -*-
"""Python Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_wH80IUpa3sOuzHhK1A7Kezpy4jpzE9
"""

#casting
a="10"
b="20"
c=a+b
print(c)

#solution
d=int("10")
e=int("20")
f=d+e
print(f)

#How to get value from user
a=input()
b=input()
c=a+b
print(c)

a=int(input())
b=int(input())
c=a+b
print(c)